///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SearchTests
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording2 recording.
    /// </summary>
    [TestModule("4768c2a5-3e9d-4700-bec2-b405e14ffacd", ModuleType.Recording, 1)]
    public partial class Recording2 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SearchTestsRepository repository.
        /// </summary>
        public static SearchTestsRepository repo = SearchTestsRepository.Instance;

        static Recording2 instance = new Recording2();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording2()
        {
            directory = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording2 Instance
        {
            get { return instance; }
        }

#region Variables

        string _directory;

        /// <summary>
        /// Gets or sets the value of variable directory.
        /// </summary>
        [TestVariable("491b84d2-e43f-4443-a2f5-92d28cbeeb67")]
        public string directory
        {
            get { return _directory; }
            set { _directory = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            directory = username();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", directory, new RecordItemIndex(1));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormEdit1UltraEdit64Bit.Element118' at 112;3.", repo.FormEdit1UltraEdit64Bit.Element118Info, new RecordItemIndex(2));
            repo.FormEdit1UltraEdit64Bit.Element118.Click("112;3");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormEdit1UltraEdit64Bit.Element59648' at 70;413.", repo.FormEdit1UltraEdit64Bit.Element59648Info, new RecordItemIndex(3));
            repo.FormEdit1UltraEdit64Bit.Element59648.Click("70;413");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormEdit1UltraEdit64Bit.Element59648' at 65;481.", repo.FormEdit1UltraEdit64Bit.Element59648Info, new RecordItemIndex(4));
            repo.FormEdit1UltraEdit64Bit.Element59648.Click("65;481");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormEdit1UltraEdit64Bit.Element59648' at 957;500.", repo.FormEdit1UltraEdit64Bit.Element59648Info, new RecordItemIndex(5));
            repo.FormEdit1UltraEdit64Bit.Element59648.Click("957;500");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormEdit1UltraEdit64Bit.Text1001' at 88;3.", repo.FormEdit1UltraEdit64Bit.Text1001Info, new RecordItemIndex(6));
            repo.FormEdit1UltraEdit64Bit.Text1001.Click("88;3");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}' with focus on 'FormEdit1UltraEdit64Bit.Text1001'.", repo.FormEdit1UltraEdit64Bit.Text1001Info, new RecordItemIndex(7));
            repo.FormEdit1UltraEdit64Bit.Text1001.PressKeys("{LControlKey down}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey up}' with focus on 'FormEdit1UltraEdit64Bit.Text1001'.", repo.FormEdit1UltraEdit64Bit.Text1001Info, new RecordItemIndex(8));
            repo.FormEdit1UltraEdit64Bit.Text1001.PressKeys("{LControlKey up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormEdit1UltraEdit64Bit.Element59648' at 855;385.", repo.FormEdit1UltraEdit64Bit.Element59648Info, new RecordItemIndex(9));
            repo.FormEdit1UltraEdit64Bit.Element59648.Click("855;385");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+F' Press with focus on 'FormEdit1UltraEdit64Bit.Element59648'.", repo.FormEdit1UltraEdit64Bit.Element59648Info, new RecordItemIndex(10));
            Keyboard.PrepareFocus(repo.FormEdit1UltraEdit64Bit.Element59648);
            Keyboard.Press(System.Windows.Forms.Keys.F | System.Windows.Forms.Keys.Control, 33, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
