///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace SearchTests
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the SearchTestsRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("69e2e14a-2afa-404b-99ea-16e1afd64364")]
    public partial class SearchTestsRepository : RepoGenBaseFolder
    {
        static SearchTestsRepository instance = new SearchTestsRepository();
        SearchTestsRepositoryFolders.UltraEdit64BitAppFolder _ultraedit64bit;
        SearchTestsRepositoryFolders.Uedit64AppFolder _uedit64;
        SearchTestsRepositoryFolders.OpenAppFolder _open;
        SearchTestsRepositoryFolders.HEXFindReplaceAppFolder _hexfindreplace;
        SearchTestsRepositoryFolders.TrialPeriodExpiringAppFolder _trialperiodexpiring;
        SearchTestsRepositoryFolders.FormCUsersBhavyaSmDownloadsUe202AppFolder _formcusersbhavyasmdownloadsue202;
        SearchTestsRepositoryFolders.UltraEditAppFolder _ultraedit;
        SearchTestsRepositoryFolders.ExplorerAppFolder _explorer;
        SearchTestsRepositoryFolders.FindAndReplaceAppFolder _findandreplace;
        SearchTestsRepositoryFolders.FormEdit1UltraEdit64BitAppFolder _formedit1ultraedit64bit;
        SearchTestsRepositoryFolders.UltraEdit64Bit1AppFolder _ultraedit64bit1;
        SearchTestsRepositoryFolders.FormEdit1UltraEdit64Bit1AppFolder _formedit1ultraedit64bit1;

        /// <summary>
        /// Gets the singleton class instance representing the SearchTestsRepository element repository.
        /// </summary>
        [RepositoryFolder("69e2e14a-2afa-404b-99ea-16e1afd64364")]
        public static SearchTestsRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public SearchTestsRepository() 
            : base("SearchTestsRepository", "/", null, 0, false, "69e2e14a-2afa-404b-99ea-16e1afd64364", ".\\RepositoryImages\\SearchTestsRepository69e2e14a.rximgres")
        {
            _ultraedit64bit = new SearchTestsRepositoryFolders.UltraEdit64BitAppFolder(this);
            _uedit64 = new SearchTestsRepositoryFolders.Uedit64AppFolder(this);
            _open = new SearchTestsRepositoryFolders.OpenAppFolder(this);
            _hexfindreplace = new SearchTestsRepositoryFolders.HEXFindReplaceAppFolder(this);
            _trialperiodexpiring = new SearchTestsRepositoryFolders.TrialPeriodExpiringAppFolder(this);
            _formcusersbhavyasmdownloadsue202 = new SearchTestsRepositoryFolders.FormCUsersBhavyaSmDownloadsUe202AppFolder(this);
            _ultraedit = new SearchTestsRepositoryFolders.UltraEditAppFolder(this);
            _explorer = new SearchTestsRepositoryFolders.ExplorerAppFolder(this);
            _findandreplace = new SearchTestsRepositoryFolders.FindAndReplaceAppFolder(this);
            _formedit1ultraedit64bit = new SearchTestsRepositoryFolders.FormEdit1UltraEdit64BitAppFolder(this);
            _ultraedit64bit1 = new SearchTestsRepositoryFolders.UltraEdit64Bit1AppFolder(this);
            _formedit1ultraedit64bit1 = new SearchTestsRepositoryFolders.FormEdit1UltraEdit64Bit1AppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("69e2e14a-2afa-404b-99ea-16e1afd64364")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The UltraEdit64Bit folder.
        /// </summary>
        [RepositoryFolder("bc1a05a2-0e50-4627-9c3e-08592780baf7")]
        public virtual SearchTestsRepositoryFolders.UltraEdit64BitAppFolder UltraEdit64Bit
        {
            get { return _ultraedit64bit; }
        }

        /// <summary>
        /// The Uedit64 folder.
        /// </summary>
        [RepositoryFolder("c9931933-4c45-45a6-a02f-0eabf7e6d625")]
        public virtual SearchTestsRepositoryFolders.Uedit64AppFolder Uedit64
        {
            get { return _uedit64; }
        }

        /// <summary>
        /// The Open folder.
        /// </summary>
        [RepositoryFolder("573a71de-b5b9-4979-86bd-98d35f5970bd")]
        public virtual SearchTestsRepositoryFolders.OpenAppFolder Open
        {
            get { return _open; }
        }

        /// <summary>
        /// The HEXFindReplace folder.
        /// </summary>
        [RepositoryFolder("b8f0144f-d73a-4ce3-b89a-4e2f0fc9955c")]
        public virtual SearchTestsRepositoryFolders.HEXFindReplaceAppFolder HEXFindReplace
        {
            get { return _hexfindreplace; }
        }

        /// <summary>
        /// The TrialPeriodExpiring folder.
        /// </summary>
        [RepositoryFolder("259e6ef9-2f3f-4da1-af60-8972394474fb")]
        public virtual SearchTestsRepositoryFolders.TrialPeriodExpiringAppFolder TrialPeriodExpiring
        {
            get { return _trialperiodexpiring; }
        }

        /// <summary>
        /// The FormCUsersBhavyaSmDownloadsUe202 folder.
        /// </summary>
        [RepositoryFolder("c72d92be-c5c9-4ea2-99c2-955280a0b5f1")]
        public virtual SearchTestsRepositoryFolders.FormCUsersBhavyaSmDownloadsUe202AppFolder FormCUsersBhavyaSmDownloadsUe202
        {
            get { return _formcusersbhavyasmdownloadsue202; }
        }

        /// <summary>
        /// The UltraEdit folder.
        /// </summary>
        [RepositoryFolder("bcbb12bc-65f1-4bd8-aa10-7c7a97089bcf")]
        public virtual SearchTestsRepositoryFolders.UltraEditAppFolder UltraEdit
        {
            get { return _ultraedit; }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("a4b701f8-a630-4ce6-8564-1531eb6e2858")]
        public virtual SearchTestsRepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }

        /// <summary>
        /// The FindAndReplace folder.
        /// </summary>
        [RepositoryFolder("a98be5a3-ef95-4ecc-aec9-d724c1ba404c")]
        public virtual SearchTestsRepositoryFolders.FindAndReplaceAppFolder FindAndReplace
        {
            get { return _findandreplace; }
        }

        /// <summary>
        /// The FormEdit1UltraEdit64Bit folder.
        /// </summary>
        [RepositoryFolder("e0b8f3be-e76f-4646-8cc1-2b90099e2251")]
        public virtual SearchTestsRepositoryFolders.FormEdit1UltraEdit64BitAppFolder FormEdit1UltraEdit64Bit
        {
            get { return _formedit1ultraedit64bit; }
        }

        /// <summary>
        /// The UltraEdit64Bit1 folder.
        /// </summary>
        [RepositoryFolder("14d3eb5d-b572-4d62-a4c6-aada384fa128")]
        public virtual SearchTestsRepositoryFolders.UltraEdit64Bit1AppFolder UltraEdit64Bit1
        {
            get { return _ultraedit64bit1; }
        }

        /// <summary>
        /// The FormEdit1UltraEdit64Bit1 folder.
        /// </summary>
        [RepositoryFolder("b8c74d4a-37e7-48e7-9c36-261f15ee2c2b")]
        public virtual SearchTestsRepositoryFolders.FormEdit1UltraEdit64Bit1AppFolder FormEdit1UltraEdit64Bit1
        {
            get { return _formedit1ultraedit64bit1; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class SearchTestsRepositoryFolders
    {
        /// <summary>
        /// The UltraEdit64BitAppFolder folder.
        /// </summary>
        [RepositoryFolder("bc1a05a2-0e50-4627-9c3e-08592780baf7")]
        public partial class UltraEdit64BitAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _applicationmenuInfo;
            RepoItemInfo _element59648Info;

            /// <summary>
            /// Creates a new UltraEdit64Bit  folder.
            /// </summary>
            public UltraEdit64BitAppFolder(RepoGenBaseFolder parentFolder) :
                    base("UltraEdit64Bit", "/form[@title='UltraEdit 64-bit']", parentFolder, 30000, null, true, "bc1a05a2-0e50-4627-9c3e-08592780baf7", "")
            {
                _applicationmenuInfo = new RepoItemInfo(this, "ApplicationMenu", "?/?/toolbar[@accessiblename=' ']/button[@accessiblename='Application menu' and @accessibledefaultaction='Press']", "", 30000, null, "1205d937-7cd8-455e-a158-ea37ce0476e2");
                _element59648Info = new RepoItemInfo(this, "Element59648", "?/?/form[@controlid='65280']/?/?/element[@controlid='59648']", ".//element[@class='EditControl']", 30000, null, "a7b0cbe8-c9a1-41ab-8e21-0da0ab4ef261");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("bc1a05a2-0e50-4627-9c3e-08592780baf7")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("bc1a05a2-0e50-4627-9c3e-08592780baf7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ApplicationMenu item.
            /// </summary>
            [RepositoryItem("1205d937-7cd8-455e-a158-ea37ce0476e2")]
            public virtual Ranorex.Button ApplicationMenu
            {
                get
                {
                    return _applicationmenuInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ApplicationMenu item info.
            /// </summary>
            [RepositoryItemInfo("1205d937-7cd8-455e-a158-ea37ce0476e2")]
            public virtual RepoItemInfo ApplicationMenuInfo
            {
                get
                {
                    return _applicationmenuInfo;
                }
            }

            /// <summary>
            /// The Element59648 item.
            /// </summary>
            [RepositoryItem("a7b0cbe8-c9a1-41ab-8e21-0da0ab4ef261")]
            public virtual Ranorex.Unknown Element59648
            {
                get
                {
                    return _element59648Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Element59648 item info.
            /// </summary>
            [RepositoryItemInfo("a7b0cbe8-c9a1-41ab-8e21-0da0ab4ef261")]
            public virtual RepoItemInfo Element59648Info
            {
                get
                {
                    return _element59648Info;
                }
            }
        }

        /// <summary>
        /// The Uedit64AppFolder folder.
        /// </summary>
        [RepositoryFolder("c9931933-4c45-45a6-a02f-0eabf7e6d625")]
        public partial class Uedit64AppFolder : RepoGenBaseFolder
        {
            SearchTestsRepositoryFolders.PopupFolder _popup;
            RepoItemInfo _openInfo;
            RepoItemInfo _findreplaceinfilesInfo;
            RepoItemInfo _findInfo;
            RepoItemInfo _hungarianInfo;
            RepoItemInfo _menuitem47Info;
            RepoItemInfo _germanInfo;
            RepoItemInfo _testInfo;
            RepoItemInfo _menuitemanysinglecharacterexceptnInfo;
            RepoItemInfo _menuitempluspluszeroormoreprecedingInfo;

            /// <summary>
            /// Creates a new Uedit64  folder.
            /// </summary>
            public Uedit64AppFolder(RepoGenBaseFolder parentFolder) :
                    base("Uedit64", "/form[@title='']", parentFolder, 30000, null, true, "c9931933-4c45-45a6-a02f-0eabf7e6d625", "")
            {
                _popup = new SearchTestsRepositoryFolders.PopupFolder(this);
                _openInfo = new RepoItemInfo(this, "Open", "?/?/toolbar[@accessiblename='']/menuitem[@accessiblename='Open']", ".//menuitem[@accessiblename='Open']", 30000, null, "bfc7f68c-c717-4259-9f2a-e43835d21ddc");
                _findreplaceinfilesInfo = new RepoItemInfo(this, "FindReplaceInFiles", "?/?/toolbar[@accessiblename='']/button[@accessiblename='Find/replace in files']", ".//button[@accessiblename='Find/replace in files']", 30000, null, "89e3955f-60e9-4f49-82c0-1e6efbeb83f0");
                _findInfo = new RepoItemInfo(this, "Find", "?/?/toolbar[@accessiblename='']/button[@accessiblename='Find']", ".//button[@accessiblename='Find']", 30000, null, "cfe8eb09-2f42-48f9-bc39-bcea31d7034f");
                _hungarianInfo = new RepoItemInfo(this, "Hungarian", "?/?/toolbar[@accessiblename='Popup']/menuitem[@accessiblename='hungarian']", ".//menuitem[@accessiblename='hungarian']", 30000, null, "74d2de27-43be-41c3-85a2-d4506e52e076");
                _menuitem47Info = new RepoItemInfo(this, "MenuItem47", "?/?/toolbar[@accessiblename='Popup']/menuitem[@accessiblename='47 ']", ".//menuitem[@accessiblename='47 ']", 30000, null, "94e7fc17-666d-4faf-8ef1-caf4a62bd35c");
                _germanInfo = new RepoItemInfo(this, "German", "?/?/toolbar[@accessiblename='Popup']/menuitem[@accessiblename='german']", ".//menuitem[@accessiblename='german']", 30000, null, "66b109bd-1ad3-4510-a67c-7ab61a7e7bc6");
                _testInfo = new RepoItemInfo(this, "Test", "?/?/toolbar[@accessiblename='Popup']/menuitem[@accessiblename='test']", ".//menuitem[@accessiblename='test']", 30000, null, "b40b4e12-8a49-4ecc-b352-594d21b4f48a");
                _menuitemanysinglecharacterexceptnInfo = new RepoItemInfo(this, "MenuItemAnySingleCharacterExceptN", "?/?/toolbar[@accessiblename='Popup']/menuitem[@accessiblename>'? Any single character (except']", ".//menuitem[@accessiblename>'? Any single character (except']", 30000, null, "6889c45b-c20b-49c8-8ce2-06b2f51399e5");
                _menuitempluspluszeroormoreprecedingInfo = new RepoItemInfo(this, "MenuItemPlusPlusZeroOrMorePreceding", "?/?/toolbar[@accessiblename='Popup']/menuitem[@accessiblename>'++ Zero or more preceding']", ".//menuitem[@accessiblename>'++ Zero or more preceding']", 30000, null, "8a5436c8-a25a-4648-9776-e92e23526791");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c9931933-4c45-45a6-a02f-0eabf7e6d625")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c9931933-4c45-45a6-a02f-0eabf7e6d625")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Open item.
            /// </summary>
            [RepositoryItem("bfc7f68c-c717-4259-9f2a-e43835d21ddc")]
            public virtual Ranorex.MenuItem Open
            {
                get
                {
                    return _openInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Open item info.
            /// </summary>
            [RepositoryItemInfo("bfc7f68c-c717-4259-9f2a-e43835d21ddc")]
            public virtual RepoItemInfo OpenInfo
            {
                get
                {
                    return _openInfo;
                }
            }

            /// <summary>
            /// The FindReplaceInFiles item.
            /// </summary>
            [RepositoryItem("89e3955f-60e9-4f49-82c0-1e6efbeb83f0")]
            public virtual Ranorex.Button FindReplaceInFiles
            {
                get
                {
                    return _findreplaceinfilesInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The FindReplaceInFiles item info.
            /// </summary>
            [RepositoryItemInfo("89e3955f-60e9-4f49-82c0-1e6efbeb83f0")]
            public virtual RepoItemInfo FindReplaceInFilesInfo
            {
                get
                {
                    return _findreplaceinfilesInfo;
                }
            }

            /// <summary>
            /// The Find item.
            /// </summary>
            [RepositoryItem("cfe8eb09-2f42-48f9-bc39-bcea31d7034f")]
            public virtual Ranorex.Button Find
            {
                get
                {
                    return _findInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Find item info.
            /// </summary>
            [RepositoryItemInfo("cfe8eb09-2f42-48f9-bc39-bcea31d7034f")]
            public virtual RepoItemInfo FindInfo
            {
                get
                {
                    return _findInfo;
                }
            }

            /// <summary>
            /// The Hungarian item.
            /// </summary>
            [RepositoryItem("74d2de27-43be-41c3-85a2-d4506e52e076")]
            public virtual Ranorex.MenuItem Hungarian
            {
                get
                {
                    return _hungarianInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Hungarian item info.
            /// </summary>
            [RepositoryItemInfo("74d2de27-43be-41c3-85a2-d4506e52e076")]
            public virtual RepoItemInfo HungarianInfo
            {
                get
                {
                    return _hungarianInfo;
                }
            }

            /// <summary>
            /// The MenuItem47 item.
            /// </summary>
            [RepositoryItem("94e7fc17-666d-4faf-8ef1-caf4a62bd35c")]
            public virtual Ranorex.MenuItem MenuItem47
            {
                get
                {
                    return _menuitem47Info.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MenuItem47 item info.
            /// </summary>
            [RepositoryItemInfo("94e7fc17-666d-4faf-8ef1-caf4a62bd35c")]
            public virtual RepoItemInfo MenuItem47Info
            {
                get
                {
                    return _menuitem47Info;
                }
            }

            /// <summary>
            /// The German item.
            /// </summary>
            [RepositoryItem("66b109bd-1ad3-4510-a67c-7ab61a7e7bc6")]
            public virtual Ranorex.MenuItem German
            {
                get
                {
                    return _germanInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The German item info.
            /// </summary>
            [RepositoryItemInfo("66b109bd-1ad3-4510-a67c-7ab61a7e7bc6")]
            public virtual RepoItemInfo GermanInfo
            {
                get
                {
                    return _germanInfo;
                }
            }

            /// <summary>
            /// The Test item.
            /// </summary>
            [RepositoryItem("b40b4e12-8a49-4ecc-b352-594d21b4f48a")]
            public virtual Ranorex.MenuItem Test
            {
                get
                {
                    return _testInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Test item info.
            /// </summary>
            [RepositoryItemInfo("b40b4e12-8a49-4ecc-b352-594d21b4f48a")]
            public virtual RepoItemInfo TestInfo
            {
                get
                {
                    return _testInfo;
                }
            }

            /// <summary>
            /// The MenuItemAnySingleCharacterExceptN item.
            /// </summary>
            [RepositoryItem("6889c45b-c20b-49c8-8ce2-06b2f51399e5")]
            public virtual Ranorex.MenuItem MenuItemAnySingleCharacterExceptN
            {
                get
                {
                    return _menuitemanysinglecharacterexceptnInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MenuItemAnySingleCharacterExceptN item info.
            /// </summary>
            [RepositoryItemInfo("6889c45b-c20b-49c8-8ce2-06b2f51399e5")]
            public virtual RepoItemInfo MenuItemAnySingleCharacterExceptNInfo
            {
                get
                {
                    return _menuitemanysinglecharacterexceptnInfo;
                }
            }

            /// <summary>
            /// The MenuItemPlusPlusZeroOrMorePreceding item.
            /// </summary>
            [RepositoryItem("8a5436c8-a25a-4648-9776-e92e23526791")]
            public virtual Ranorex.MenuItem MenuItemPlusPlusZeroOrMorePreceding
            {
                get
                {
                    return _menuitempluspluszeroormoreprecedingInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MenuItemPlusPlusZeroOrMorePreceding item info.
            /// </summary>
            [RepositoryItemInfo("8a5436c8-a25a-4648-9776-e92e23526791")]
            public virtual RepoItemInfo MenuItemPlusPlusZeroOrMorePrecedingInfo
            {
                get
                {
                    return _menuitempluspluszeroormoreprecedingInfo;
                }
            }

            /// <summary>
            /// The Popup folder.
            /// </summary>
            [RepositoryFolder("a72d25ca-80d6-4ca0-810e-1282aedf40bf")]
            public virtual SearchTestsRepositoryFolders.PopupFolder Popup
            {
                get { return _popup; }
            }
        }

        /// <summary>
        /// The PopupFolder folder.
        /// </summary>
        [RepositoryFolder("a72d25ca-80d6-4ca0-810e-1282aedf40bf")]
        public partial class PopupFolder : RepoGenBaseFolder
        {
            RepoItemInfo _menuitempercentstartoflineInfo;
            RepoItemInfo _menuitemplusoneormoreprecedingcharInfo;
            RepoItemInfo _menuitemcaretnlinefeedlfonlyunixInfo;
            RepoItemInfo _menuitemcaretrcarriagereturncronlyInfo;

            /// <summary>
            /// Creates a new Popup  folder.
            /// </summary>
            public PopupFolder(RepoGenBaseFolder parentFolder) :
                    base("Popup", "?/?/toolbar[@accessiblename='Popup']", parentFolder, 30000, null, false, "a72d25ca-80d6-4ca0-810e-1282aedf40bf", "")
            {
                _menuitempercentstartoflineInfo = new RepoItemInfo(this, "MenuItemPercentStartOfLine", "menuitem[@accessiblename='% Start of line']", "", 30000, null, "e1d8edc2-2485-4c3c-9ec5-6e1548821d41");
                _menuitemplusoneormoreprecedingcharInfo = new RepoItemInfo(this, "MenuItemPlusOneOrMorePrecedingChar", "menuitem[@accessiblename>'+ One or more preceding']", "", 30000, null, "ec55663f-cf73-4d53-b1c5-f56245d2ee8c");
                _menuitemcaretnlinefeedlfonlyunixInfo = new RepoItemInfo(this, "MenuItemCaretnLineFeedLFOnlyUnix", "menuitem[@accessiblename>'^n Line feed (LF only)(Unix']", "", 30000, null, "fbb85b1d-9587-4614-938b-076911bbc73a");
                _menuitemcaretrcarriagereturncronlyInfo = new RepoItemInfo(this, "MenuItemCaretrCarriageReturnCROnly", "menuitem[@accessiblename>'^r Carriage return (CR only)(Mac']", "", 30000, null, "a446e824-ce26-478b-a2a9-ab6e9bf9a6eb");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a72d25ca-80d6-4ca0-810e-1282aedf40bf")]
            public virtual Ranorex.ToolBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ToolBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a72d25ca-80d6-4ca0-810e-1282aedf40bf")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MenuItemPercentStartOfLine item.
            /// </summary>
            [RepositoryItem("e1d8edc2-2485-4c3c-9ec5-6e1548821d41")]
            public virtual Ranorex.MenuItem MenuItemPercentStartOfLine
            {
                get
                {
                    return _menuitempercentstartoflineInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MenuItemPercentStartOfLine item info.
            /// </summary>
            [RepositoryItemInfo("e1d8edc2-2485-4c3c-9ec5-6e1548821d41")]
            public virtual RepoItemInfo MenuItemPercentStartOfLineInfo
            {
                get
                {
                    return _menuitempercentstartoflineInfo;
                }
            }

            /// <summary>
            /// The MenuItemPlusOneOrMorePrecedingChar item.
            /// </summary>
            [RepositoryItem("ec55663f-cf73-4d53-b1c5-f56245d2ee8c")]
            public virtual Ranorex.MenuItem MenuItemPlusOneOrMorePrecedingChar
            {
                get
                {
                    return _menuitemplusoneormoreprecedingcharInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MenuItemPlusOneOrMorePrecedingChar item info.
            /// </summary>
            [RepositoryItemInfo("ec55663f-cf73-4d53-b1c5-f56245d2ee8c")]
            public virtual RepoItemInfo MenuItemPlusOneOrMorePrecedingCharInfo
            {
                get
                {
                    return _menuitemplusoneormoreprecedingcharInfo;
                }
            }

            /// <summary>
            /// The MenuItemCaretnLineFeedLFOnlyUnix item.
            /// </summary>
            [RepositoryItem("fbb85b1d-9587-4614-938b-076911bbc73a")]
            public virtual Ranorex.MenuItem MenuItemCaretnLineFeedLFOnlyUnix
            {
                get
                {
                    return _menuitemcaretnlinefeedlfonlyunixInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MenuItemCaretnLineFeedLFOnlyUnix item info.
            /// </summary>
            [RepositoryItemInfo("fbb85b1d-9587-4614-938b-076911bbc73a")]
            public virtual RepoItemInfo MenuItemCaretnLineFeedLFOnlyUnixInfo
            {
                get
                {
                    return _menuitemcaretnlinefeedlfonlyunixInfo;
                }
            }

            /// <summary>
            /// The MenuItemCaretrCarriageReturnCROnly item.
            /// </summary>
            [RepositoryItem("a446e824-ce26-478b-a2a9-ab6e9bf9a6eb")]
            public virtual Ranorex.MenuItem MenuItemCaretrCarriageReturnCROnly
            {
                get
                {
                    return _menuitemcaretrcarriagereturncronlyInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MenuItemCaretrCarriageReturnCROnly item info.
            /// </summary>
            [RepositoryItemInfo("a446e824-ce26-478b-a2a9-ab6e9bf9a6eb")]
            public virtual RepoItemInfo MenuItemCaretrCarriageReturnCROnlyInfo
            {
                get
                {
                    return _menuitemcaretrcarriagereturncronlyInfo;
                }
            }
        }

        /// <summary>
        /// The OpenAppFolder folder.
        /// </summary>
        [RepositoryFolder("573a71de-b5b9-4979-86bd-98d35f5970bd")]
        public partial class OpenAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _text1148Info;
            RepoItemInfo _buttonopenInfo;

            /// <summary>
            /// Creates a new Open  folder.
            /// </summary>
            public OpenAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Open", "/form[@title='Open']", parentFolder, 30000, null, true, "573a71de-b5b9-4979-86bd-98d35f5970bd", "")
            {
                _text1148Info = new RepoItemInfo(this, "Text1148", "?/?/text[@controlid='1148']", "?/?/text[@controlid='1148']", 30000, null, "0d63aa9e-8695-472b-b358-415279c0cd2d");
                _buttonopenInfo = new RepoItemInfo(this, "ButtonOpen", "button[@text='&Open']", "button[@text='&Open']", 30000, null, "5d1bd53c-188b-4bb6-8c4d-0754da2c1283");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("573a71de-b5b9-4979-86bd-98d35f5970bd")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("573a71de-b5b9-4979-86bd-98d35f5970bd")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Text1148 item.
            /// </summary>
            [RepositoryItem("0d63aa9e-8695-472b-b358-415279c0cd2d")]
            public virtual Ranorex.Text Text1148
            {
                get
                {
                    return _text1148Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text1148 item info.
            /// </summary>
            [RepositoryItemInfo("0d63aa9e-8695-472b-b358-415279c0cd2d")]
            public virtual RepoItemInfo Text1148Info
            {
                get
                {
                    return _text1148Info;
                }
            }

            /// <summary>
            /// The ButtonOpen item.
            /// </summary>
            [RepositoryItem("5d1bd53c-188b-4bb6-8c4d-0754da2c1283")]
            public virtual Ranorex.Button ButtonOpen
            {
                get
                {
                    return _buttonopenInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOpen item info.
            /// </summary>
            [RepositoryItemInfo("5d1bd53c-188b-4bb6-8c4d-0754da2c1283")]
            public virtual RepoItemInfo ButtonOpenInfo
            {
                get
                {
                    return _buttonopenInfo;
                }
            }
        }

        /// <summary>
        /// The HEXFindReplaceAppFolder folder.
        /// </summary>
        [RepositoryFolder("b8f0144f-d73a-4ce3-b89a-4e2f0fc9955c")]
        public partial class HEXFindReplaceAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _tabpagelist1001Info;
            RepoItemInfo _findasciiInfo;
            RepoItemInfo _text1687Info;
            RepoItemInfo _checkboxmatchcaseInfo;
            RepoItemInfo _buttonnextInfo;
            RepoItemInfo _buttonInfo;
            RepoItemInfo _replaceInfo;
            RepoItemInfo _button1Info;
            RepoItemInfo _text1695Info;
            RepoItemInfo _findInfo;
            RepoItemInfo _regularexpressionsasciionlyInfo;
            RepoItemInfo _button2Info;
            RepoItemInfo _button3Info;

            /// <summary>
            /// Creates a new HEXFindReplace  folder.
            /// </summary>
            public HEXFindReplaceAppFolder(RepoGenBaseFolder parentFolder) :
                    base("HEXFindReplace", "/form[@title='HEX Find/Replace']", parentFolder, 30000, null, true, "b8f0144f-d73a-4ce3-b89a-4e2f0fc9955c", "")
            {
                _tabpagelist1001Info = new RepoItemInfo(this, "TabPageList1001", "?/?/tabpagelist[@controlid='1001']", "?/?/tabpagelist[@controlid='1001']", 30000, null, "916c910d-e7b5-43c4-b2d9-ab60a55bfd06");
                _findasciiInfo = new RepoItemInfo(this, "FindASCII", ".//container[@class='#32770']/checkbox[@text='Find A&SCII']", ".//checkbox[@text='Find A&SCII']", 30000, null, "0cea3d81-6632-4e8a-a61e-4c1bdea5cb18");
                _text1687Info = new RepoItemInfo(this, "Text1687", ".//container[@class='#32770']/text[@controlid='1687' and @processname='uedit64']", "", 30000, null, "1bbab43b-34f0-4a0d-828e-351835cdc78d");
                _checkboxmatchcaseInfo = new RepoItemInfo(this, "CheckBoxMatchCase", ".//container[@class='#32770']/checkbox[@text='&Match case']", ".//checkbox[@text='&Match case']", 30000, null, "d681df9f-ad22-459d-aa86-3e63c039ac75");
                _buttonnextInfo = new RepoItemInfo(this, "ButtonNext", ".//container[@class='#32770']/button[@text='&Next']", ".//button[@text='&Next']", 30000, null, "1c098b0e-4692-4b71-b456-bdd50f73a35e");
                _buttonInfo = new RepoItemInfo(this, "Button", ".//container[@class='#32770']/button[@controlid='1692']", ".//button[@controlid='1692']", 30000, null, "d59b4fd2-e46e-470d-a753-18d1a8e9deb0");
                _replaceInfo = new RepoItemInfo(this, "Replace", "?/?/tabpagelist[@controlid='1001']/tabpage[@title='Replace']", ".//tabpage[@title='Replace']", 30000, null, "9ef2d6bd-abf6-4612-bde8-ae0d0c8f0716");
                _button1Info = new RepoItemInfo(this, "Button1", ".//container[@class='#32770']/button[@controlid='1697']", ".//button[@controlid='1697']", 30000, null, "1b5859fd-0bfc-49e9-a9fa-2d1e5fd27f9e");
                _text1695Info = new RepoItemInfo(this, "Text1695", ".//container[@class='#32770']/text[@controlid='1695']", ".//text[@controlid='1695']", 30000, null, "f49f83b1-d040-4199-a944-c36e48aa2fef");
                _findInfo = new RepoItemInfo(this, "Find", "?/?/tabpagelist[@controlid='1001']/tabpage[@title='Find']", ".//tabpage[@title='Find']", 30000, null, "eede8e69-6850-4146-884d-0156e4960f7d");
                _regularexpressionsasciionlyInfo = new RepoItemInfo(this, "RegularExpressionsASCIIOnly", ".//container[@class='#32770']/checkbox[@text>'Regular &expressions (ASCII']", ".//checkbox[@text>'Regular &expressions (ASCII']", 30000, null, "4b858aac-d22e-4489-a7a8-e7ed643a8784");
                _button2Info = new RepoItemInfo(this, "Button2", ".//container[@class='#32770']/button[@controlid='1693']", ".//button[@controlid='1693']", 30000, null, "5afacf8a-060d-486e-88c9-f9e99509a367");
                _button3Info = new RepoItemInfo(this, "Button3", ".//container[@class='#32770']/button[@controlid='1698']", ".//button[@controlid='1698']", 30000, null, "4df991a1-328b-40b0-8cbb-d8a6f1635f97");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b8f0144f-d73a-4ce3-b89a-4e2f0fc9955c")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b8f0144f-d73a-4ce3-b89a-4e2f0fc9955c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TabPageList1001 item.
            /// </summary>
            [RepositoryItem("916c910d-e7b5-43c4-b2d9-ab60a55bfd06")]
            public virtual Ranorex.TabPageList TabPageList1001
            {
                get
                {
                    return _tabpagelist1001Info.CreateAdapter<Ranorex.TabPageList>(true);
                }
            }

            /// <summary>
            /// The TabPageList1001 item info.
            /// </summary>
            [RepositoryItemInfo("916c910d-e7b5-43c4-b2d9-ab60a55bfd06")]
            public virtual RepoItemInfo TabPageList1001Info
            {
                get
                {
                    return _tabpagelist1001Info;
                }
            }

            /// <summary>
            /// The FindASCII item.
            /// </summary>
            [RepositoryItem("0cea3d81-6632-4e8a-a61e-4c1bdea5cb18")]
            public virtual Ranorex.CheckBox FindASCII
            {
                get
                {
                    return _findasciiInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The FindASCII item info.
            /// </summary>
            [RepositoryItemInfo("0cea3d81-6632-4e8a-a61e-4c1bdea5cb18")]
            public virtual RepoItemInfo FindASCIIInfo
            {
                get
                {
                    return _findasciiInfo;
                }
            }

            /// <summary>
            /// The Text1687 item.
            /// </summary>
            [RepositoryItem("1bbab43b-34f0-4a0d-828e-351835cdc78d")]
            public virtual Ranorex.Text Text1687
            {
                get
                {
                    return _text1687Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text1687 item info.
            /// </summary>
            [RepositoryItemInfo("1bbab43b-34f0-4a0d-828e-351835cdc78d")]
            public virtual RepoItemInfo Text1687Info
            {
                get
                {
                    return _text1687Info;
                }
            }

            /// <summary>
            /// The CheckBoxMatchCase item.
            /// </summary>
            [RepositoryItem("d681df9f-ad22-459d-aa86-3e63c039ac75")]
            public virtual Ranorex.CheckBox CheckBoxMatchCase
            {
                get
                {
                    return _checkboxmatchcaseInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The CheckBoxMatchCase item info.
            /// </summary>
            [RepositoryItemInfo("d681df9f-ad22-459d-aa86-3e63c039ac75")]
            public virtual RepoItemInfo CheckBoxMatchCaseInfo
            {
                get
                {
                    return _checkboxmatchcaseInfo;
                }
            }

            /// <summary>
            /// The ButtonNext item.
            /// </summary>
            [RepositoryItem("1c098b0e-4692-4b71-b456-bdd50f73a35e")]
            public virtual Ranorex.Button ButtonNext
            {
                get
                {
                    return _buttonnextInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonNext item info.
            /// </summary>
            [RepositoryItemInfo("1c098b0e-4692-4b71-b456-bdd50f73a35e")]
            public virtual RepoItemInfo ButtonNextInfo
            {
                get
                {
                    return _buttonnextInfo;
                }
            }

            /// <summary>
            /// The Button item.
            /// </summary>
            [RepositoryItem("d59b4fd2-e46e-470d-a753-18d1a8e9deb0")]
            public virtual Ranorex.Button Button
            {
                get
                {
                    return _buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button item info.
            /// </summary>
            [RepositoryItemInfo("d59b4fd2-e46e-470d-a753-18d1a8e9deb0")]
            public virtual RepoItemInfo ButtonInfo
            {
                get
                {
                    return _buttonInfo;
                }
            }

            /// <summary>
            /// The Replace item.
            /// </summary>
            [RepositoryItem("9ef2d6bd-abf6-4612-bde8-ae0d0c8f0716")]
            public virtual Ranorex.TabPage Replace
            {
                get
                {
                    return _replaceInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Replace item info.
            /// </summary>
            [RepositoryItemInfo("9ef2d6bd-abf6-4612-bde8-ae0d0c8f0716")]
            public virtual RepoItemInfo ReplaceInfo
            {
                get
                {
                    return _replaceInfo;
                }
            }

            /// <summary>
            /// The Button1 item.
            /// </summary>
            [RepositoryItem("1b5859fd-0bfc-49e9-a9fa-2d1e5fd27f9e")]
            public virtual Ranorex.Button Button1
            {
                get
                {
                    return _button1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button1 item info.
            /// </summary>
            [RepositoryItemInfo("1b5859fd-0bfc-49e9-a9fa-2d1e5fd27f9e")]
            public virtual RepoItemInfo Button1Info
            {
                get
                {
                    return _button1Info;
                }
            }

            /// <summary>
            /// The Text1695 item.
            /// </summary>
            [RepositoryItem("f49f83b1-d040-4199-a944-c36e48aa2fef")]
            public virtual Ranorex.Text Text1695
            {
                get
                {
                    return _text1695Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text1695 item info.
            /// </summary>
            [RepositoryItemInfo("f49f83b1-d040-4199-a944-c36e48aa2fef")]
            public virtual RepoItemInfo Text1695Info
            {
                get
                {
                    return _text1695Info;
                }
            }

            /// <summary>
            /// The Find item.
            /// </summary>
            [RepositoryItem("eede8e69-6850-4146-884d-0156e4960f7d")]
            public virtual Ranorex.TabPage Find
            {
                get
                {
                    return _findInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Find item info.
            /// </summary>
            [RepositoryItemInfo("eede8e69-6850-4146-884d-0156e4960f7d")]
            public virtual RepoItemInfo FindInfo
            {
                get
                {
                    return _findInfo;
                }
            }

            /// <summary>
            /// The RegularExpressionsASCIIOnly item.
            /// </summary>
            [RepositoryItem("4b858aac-d22e-4489-a7a8-e7ed643a8784")]
            public virtual Ranorex.CheckBox RegularExpressionsASCIIOnly
            {
                get
                {
                    return _regularexpressionsasciionlyInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The RegularExpressionsASCIIOnly item info.
            /// </summary>
            [RepositoryItemInfo("4b858aac-d22e-4489-a7a8-e7ed643a8784")]
            public virtual RepoItemInfo RegularExpressionsASCIIOnlyInfo
            {
                get
                {
                    return _regularexpressionsasciionlyInfo;
                }
            }

            /// <summary>
            /// The Button2 item.
            /// </summary>
            [RepositoryItem("5afacf8a-060d-486e-88c9-f9e99509a367")]
            public virtual Ranorex.Button Button2
            {
                get
                {
                    return _button2Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button2 item info.
            /// </summary>
            [RepositoryItemInfo("5afacf8a-060d-486e-88c9-f9e99509a367")]
            public virtual RepoItemInfo Button2Info
            {
                get
                {
                    return _button2Info;
                }
            }

            /// <summary>
            /// The Button3 item.
            /// </summary>
            [RepositoryItem("4df991a1-328b-40b0-8cbb-d8a6f1635f97")]
            public virtual Ranorex.Button Button3
            {
                get
                {
                    return _button3Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button3 item info.
            /// </summary>
            [RepositoryItemInfo("4df991a1-328b-40b0-8cbb-d8a6f1635f97")]
            public virtual RepoItemInfo Button3Info
            {
                get
                {
                    return _button3Info;
                }
            }
        }

        /// <summary>
        /// The TrialPeriodExpiringAppFolder folder.
        /// </summary>
        [RepositoryFolder("259e6ef9-2f3f-4da1-af60-8972394474fb")]
        public partial class TrialPeriodExpiringAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _closeInfo;

            /// <summary>
            /// Creates a new TrialPeriodExpiring  folder.
            /// </summary>
            public TrialPeriodExpiringAppFolder(RepoGenBaseFolder parentFolder) :
                    base("TrialPeriodExpiring", "/form[@title='Trial Period Expiring']", parentFolder, 30000, null, true, "259e6ef9-2f3f-4da1-af60-8972394474fb", "")
            {
                _closeInfo = new RepoItemInfo(this, "Close", "form[@name='Trial Period Expiring']/?/?/button[@name='Close']", "?/titlebar/button[@name='Close']", 30000, null, "7ef438ae-f529-4063-883f-defb341a6ef1");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("259e6ef9-2f3f-4da1-af60-8972394474fb")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("259e6ef9-2f3f-4da1-af60-8972394474fb")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("7ef438ae-f529-4063-883f-defb341a6ef1")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("7ef438ae-f529-4063-883f-defb341a6ef1")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }
        }

        /// <summary>
        /// The FormCUsersBhavyaSmDownloadsUe202AppFolder folder.
        /// </summary>
        [RepositoryFolder("c72d92be-c5c9-4ea2-99c2-955280a0b5f1")]
        public partial class FormCUsersBhavyaSmDownloadsUe202AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _element59648Info;
            RepoItemInfo _homeInfo;

            /// <summary>
            /// Creates a new FormCUsersBhavyaSmDownloadsUe202  folder.
            /// </summary>
            public FormCUsersBhavyaSmDownloadsUe202AppFolder(RepoGenBaseFolder parentFolder) :
                    base("FormCUsersBhavyaSmDownloadsUe202", "/form[@title>'[C:\\Users\\bhavya.sm\\Downl']", parentFolder, 30000, null, true, "c72d92be-c5c9-4ea2-99c2-955280a0b5f1", "")
            {
                _element59648Info = new RepoItemInfo(this, "Element59648", "?/?/form[@controlid='65280']/?/?/element[@controlid='59648']", ".//element[@controlid='59648' and @class='EditControl']", 30000, null, "3ab3e610-204f-4118-88a0-71e07da8d412");
                _homeInfo = new RepoItemInfo(this, "Home", "?/?/toolbar[@accessiblename=' ']/?/?/tabpage[@accessiblename='Home']", ".//tabpage[@accessiblename='Home']", 30000, null, "876b42b1-a0b9-4b12-9c44-07567fa3649f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c72d92be-c5c9-4ea2-99c2-955280a0b5f1")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c72d92be-c5c9-4ea2-99c2-955280a0b5f1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Element59648 item.
            /// </summary>
            [RepositoryItem("3ab3e610-204f-4118-88a0-71e07da8d412")]
            public virtual Ranorex.Unknown Element59648
            {
                get
                {
                    return _element59648Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Element59648 item info.
            /// </summary>
            [RepositoryItemInfo("3ab3e610-204f-4118-88a0-71e07da8d412")]
            public virtual RepoItemInfo Element59648Info
            {
                get
                {
                    return _element59648Info;
                }
            }

            /// <summary>
            /// The Home item.
            /// </summary>
            [RepositoryItem("876b42b1-a0b9-4b12-9c44-07567fa3649f")]
            public virtual Ranorex.TabPage Home
            {
                get
                {
                    return _homeInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Home item info.
            /// </summary>
            [RepositoryItemInfo("876b42b1-a0b9-4b12-9c44-07567fa3649f")]
            public virtual RepoItemInfo HomeInfo
            {
                get
                {
                    return _homeInfo;
                }
            }
        }

        /// <summary>
        /// The UltraEditAppFolder folder.
        /// </summary>
        [RepositoryFolder("bcbb12bc-65f1-4bd8-aa10-7c7a97089bcf")]
        public partial class UltraEditAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _ultraeditInfo;
            RepoItemInfo _text65535Info;
            RepoItemInfo _buttonokInfo;

            /// <summary>
            /// Creates a new UltraEdit  folder.
            /// </summary>
            public UltraEditAppFolder(RepoGenBaseFolder parentFolder) :
                    base("UltraEdit", "/form[@title='UltraEdit']", parentFolder, 30000, null, true, "bcbb12bc-65f1-4bd8-aa10-7c7a97089bcf", "")
            {
                _ultraeditInfo = new RepoItemInfo(this, "UltraEdit", "form[@name='UltraEdit']", "form[@name='UltraEdit']", 30000, null, "2a76a92f-0c38-437e-b8ff-eaa3fdf16dcf");
                _text65535Info = new RepoItemInfo(this, "Text65535", "text[@controlid='65535']", "text[@controlid='65535']", 30000, null, "a118a064-1e67-4238-a6cc-d55008532c96");
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "button[@text='OK']", "button[@text='OK']", 30000, null, "bfac1349-d6bf-4b4a-ac79-77823c549579");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("bcbb12bc-65f1-4bd8-aa10-7c7a97089bcf")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("bcbb12bc-65f1-4bd8-aa10-7c7a97089bcf")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The UltraEdit item.
            /// </summary>
            [RepositoryItem("2a76a92f-0c38-437e-b8ff-eaa3fdf16dcf")]
            public virtual Ranorex.Form UltraEdit
            {
                get
                {
                    return _ultraeditInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The UltraEdit item info.
            /// </summary>
            [RepositoryItemInfo("2a76a92f-0c38-437e-b8ff-eaa3fdf16dcf")]
            public virtual RepoItemInfo UltraEditInfo
            {
                get
                {
                    return _ultraeditInfo;
                }
            }

            /// <summary>
            /// The Text65535 item.
            /// </summary>
            [RepositoryItem("a118a064-1e67-4238-a6cc-d55008532c96")]
            public virtual Ranorex.Text Text65535
            {
                get
                {
                    return _text65535Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text65535 item info.
            /// </summary>
            [RepositoryItemInfo("a118a064-1e67-4238-a6cc-d55008532c96")]
            public virtual RepoItemInfo Text65535Info
            {
                get
                {
                    return _text65535Info;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("bfac1349-d6bf-4b4a-ac79-77823c549579")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("bfac1349-d6bf-4b4a-ac79-77823c549579")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }
        }

        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("a4b701f8-a630-4ce6-8564-1531eb6e2858")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _iconInfo;
            RepoItemInfo _appid6d8093776af0444b8957a3773f02Info;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/menubar[@processname='explorer']", parentFolder, 30000, null, true, "a4b701f8-a630-4ce6-8564-1531eb6e2858", "")
            {
                _iconInfo = new RepoItemInfo(this, "Icon", ".//container[@automationid='TaskbarFrame']/?/?/button[@automationid='Appid: {6D809377-6AF0-444B-8957-A3773F02200E}\\IDM Computer Solutions\\UltraEdit\\uedit64.exe']/picture[@automationid='Icon']", ".//button[@automationid='Appid: {6D809377-6AF0-444B-8957-A3773F02200E}\\IDM Computer Solutions\\UltraEdit\\uedit64.exe']/picture[@automationid='Icon']", 30000, null, "6499d527-1e55-4c3e-8bd6-8d81e4f72c0c");
                _appid6d8093776af0444b8957a3773f02Info = new RepoItemInfo(this, "Appid6D8093776AF0444B8957A3773F02", ".//container[@automationid='TaskbarFrame']/container[@automationid='TaskbarFrameRepeater']/button[@automationid='Appid: {6D809377-6AF0-444B-8957-A3773F02200E}\\IDM Computer Solutions\\UltraEdit\\uedit64.exe']", ".//button[@automationid='Appid: {6D809377-6AF0-444B-8957-A3773F02200E}\\IDM Computer Solutions\\UltraEdit\\uedit64.exe']", 30000, null, "b0795d06-f2c1-4b50-a620-8c5eeb729052");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a4b701f8-a630-4ce6-8564-1531eb6e2858")]
            public virtual Ranorex.MenuBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MenuBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a4b701f8-a630-4ce6-8564-1531eb6e2858")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Icon item.
            /// </summary>
            [RepositoryItem("6499d527-1e55-4c3e-8bd6-8d81e4f72c0c")]
            public virtual Ranorex.Picture Icon
            {
                get
                {
                    return _iconInfo.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The Icon item info.
            /// </summary>
            [RepositoryItemInfo("6499d527-1e55-4c3e-8bd6-8d81e4f72c0c")]
            public virtual RepoItemInfo IconInfo
            {
                get
                {
                    return _iconInfo;
                }
            }

            /// <summary>
            /// The Appid6D8093776AF0444B8957A3773F02 item.
            /// </summary>
            [RepositoryItem("b0795d06-f2c1-4b50-a620-8c5eeb729052")]
            public virtual Ranorex.Button Appid6D8093776AF0444B8957A3773F02
            {
                get
                {
                    return _appid6d8093776af0444b8957a3773f02Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Appid6D8093776AF0444B8957A3773F02 item info.
            /// </summary>
            [RepositoryItemInfo("b0795d06-f2c1-4b50-a620-8c5eeb729052")]
            public virtual RepoItemInfo Appid6D8093776AF0444B8957A3773F02Info
            {
                get
                {
                    return _appid6d8093776af0444b8957a3773f02Info;
                }
            }
        }

        /// <summary>
        /// The FindAndReplaceAppFolder folder.
        /// </summary>
        [RepositoryFolder("a98be5a3-ef95-4ecc-aec9-d724c1ba404c")]
        public partial class FindAndReplaceAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonInfo;
            RepoItemInfo _findinfilesInfo;
            RepoItemInfo _findInfo;
            RepoItemInfo _text2541Info;

            /// <summary>
            /// Creates a new FindAndReplace  folder.
            /// </summary>
            public FindAndReplaceAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FindAndReplace", "/form[@title='Find and Replace']", parentFolder, 30000, null, true, "a98be5a3-ef95-4ecc-aec9-d724c1ba404c", "")
            {
                _buttonInfo = new RepoItemInfo(this, "Button", ".//container[@class='#32770']/button[@controlid='2534']", ".//button[@controlid='2534']", 30000, null, "eef96a06-c7b2-47c0-8c82-cfb13b2792fb");
                _findinfilesInfo = new RepoItemInfo(this, "FindInFiles", ".//tabpagelist[@controlid='1205']/tabpage[@title='Find in Files']", ".//tabpage[@title='Find in Files']", 30000, null, "ad0be894-6660-4704-a7b8-0f7885b9c4d2");
                _findInfo = new RepoItemInfo(this, "Find", "?/?/tabpagelist[@controlid='1205']/tabpage[@title='Find']", ".//tabpage[@title='Find']", 30000, null, "0e7d001b-4167-4fe7-94d0-ff6acb30a1ad");
                _text2541Info = new RepoItemInfo(this, "Text2541", ".//container[@class='#32770']/text[@controlid='2541' and @processname='uedit64']", ".//text[@controlid='2541']", 30000, null, "14766583-4927-4a5e-966b-c8ed904c6321");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a98be5a3-ef95-4ecc-aec9-d724c1ba404c")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a98be5a3-ef95-4ecc-aec9-d724c1ba404c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Button item.
            /// </summary>
            [RepositoryItem("eef96a06-c7b2-47c0-8c82-cfb13b2792fb")]
            public virtual Ranorex.Button Button
            {
                get
                {
                    return _buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button item info.
            /// </summary>
            [RepositoryItemInfo("eef96a06-c7b2-47c0-8c82-cfb13b2792fb")]
            public virtual RepoItemInfo ButtonInfo
            {
                get
                {
                    return _buttonInfo;
                }
            }

            /// <summary>
            /// The FindInFiles item.
            /// </summary>
            [RepositoryItem("ad0be894-6660-4704-a7b8-0f7885b9c4d2")]
            public virtual Ranorex.TabPage FindInFiles
            {
                get
                {
                    return _findinfilesInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The FindInFiles item info.
            /// </summary>
            [RepositoryItemInfo("ad0be894-6660-4704-a7b8-0f7885b9c4d2")]
            public virtual RepoItemInfo FindInFilesInfo
            {
                get
                {
                    return _findinfilesInfo;
                }
            }

            /// <summary>
            /// The Find item.
            /// </summary>
            [RepositoryItem("0e7d001b-4167-4fe7-94d0-ff6acb30a1ad")]
            public virtual Ranorex.TabPage Find
            {
                get
                {
                    return _findInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Find item info.
            /// </summary>
            [RepositoryItemInfo("0e7d001b-4167-4fe7-94d0-ff6acb30a1ad")]
            public virtual RepoItemInfo FindInfo
            {
                get
                {
                    return _findInfo;
                }
            }

            /// <summary>
            /// The Text2541 item.
            /// </summary>
            [RepositoryItem("14766583-4927-4a5e-966b-c8ed904c6321")]
            public virtual Ranorex.Text Text2541
            {
                get
                {
                    return _text2541Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text2541 item info.
            /// </summary>
            [RepositoryItemInfo("14766583-4927-4a5e-966b-c8ed904c6321")]
            public virtual RepoItemInfo Text2541Info
            {
                get
                {
                    return _text2541Info;
                }
            }
        }

        /// <summary>
        /// The FormEdit1UltraEdit64BitAppFolder folder.
        /// </summary>
        [RepositoryFolder("e0b8f3be-e76f-4646-8cc1-2b90099e2251")]
        public partial class FormEdit1UltraEdit64BitAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _applicationmenuInfo;
            RepoItemInfo _element118Info;
            RepoItemInfo _element59648Info;
            RepoItemInfo _text1001Info;

            /// <summary>
            /// Creates a new FormEdit1UltraEdit64Bit  folder.
            /// </summary>
            public FormEdit1UltraEdit64BitAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FormEdit1UltraEdit64Bit", "/form[@title>'[Edit1] - UltraEdit 64-bi']", parentFolder, 30000, null, true, "e0b8f3be-e76f-4646-8cc1-2b90099e2251", "")
            {
                _applicationmenuInfo = new RepoItemInfo(this, "ApplicationMenu", "?/?/toolbar[@accessiblename=' ']/button[@accessiblename='Application menu']", ".//button[@accessiblename='Application menu']", 30000, null, "6f09845c-1b37-4aa0-adbd-483e405fe632");
                _element118Info = new RepoItemInfo(this, "Element118", "container[@controlid='59648']/form[@controlid='65280']//element[@controlid='118']", ".//element[@controlid='118']", 30000, null, "d228532e-0729-4bf3-90da-1f40913f4b5c");
                _element59648Info = new RepoItemInfo(this, "Element59648", "?/?/form[@controlid='65280']/?/?/element[@controlid='59648']", ".//element[@controlid='59648' and @class='EditControl']", 30000, null, "56ff6c3e-21d8-4b34-94f1-6b905aed382e");
                _text1001Info = new RepoItemInfo(this, "Text1001", "container[@controlid='59648']/form[@controlid='65280']//combobox[@controlid='113']/text[@controlid='1001']", ".//text[@controlid='1001']", 30000, null, "e4bf4787-59f7-4127-a75d-8990629a93fb");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e0b8f3be-e76f-4646-8cc1-2b90099e2251")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e0b8f3be-e76f-4646-8cc1-2b90099e2251")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ApplicationMenu item.
            /// </summary>
            [RepositoryItem("6f09845c-1b37-4aa0-adbd-483e405fe632")]
            public virtual Ranorex.Button ApplicationMenu
            {
                get
                {
                    return _applicationmenuInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ApplicationMenu item info.
            /// </summary>
            [RepositoryItemInfo("6f09845c-1b37-4aa0-adbd-483e405fe632")]
            public virtual RepoItemInfo ApplicationMenuInfo
            {
                get
                {
                    return _applicationmenuInfo;
                }
            }

            /// <summary>
            /// The Element118 item.
            /// </summary>
            [RepositoryItem("d228532e-0729-4bf3-90da-1f40913f4b5c")]
            public virtual Ranorex.Unknown Element118
            {
                get
                {
                    return _element118Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Element118 item info.
            /// </summary>
            [RepositoryItemInfo("d228532e-0729-4bf3-90da-1f40913f4b5c")]
            public virtual RepoItemInfo Element118Info
            {
                get
                {
                    return _element118Info;
                }
            }

            /// <summary>
            /// The Element59648 item.
            /// </summary>
            [RepositoryItem("56ff6c3e-21d8-4b34-94f1-6b905aed382e")]
            public virtual Ranorex.Unknown Element59648
            {
                get
                {
                    return _element59648Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Element59648 item info.
            /// </summary>
            [RepositoryItemInfo("56ff6c3e-21d8-4b34-94f1-6b905aed382e")]
            public virtual RepoItemInfo Element59648Info
            {
                get
                {
                    return _element59648Info;
                }
            }

            /// <summary>
            /// The Text1001 item.
            /// </summary>
            [RepositoryItem("e4bf4787-59f7-4127-a75d-8990629a93fb")]
            public virtual Ranorex.Text Text1001
            {
                get
                {
                    return _text1001Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text1001 item info.
            /// </summary>
            [RepositoryItemInfo("e4bf4787-59f7-4127-a75d-8990629a93fb")]
            public virtual RepoItemInfo Text1001Info
            {
                get
                {
                    return _text1001Info;
                }
            }
        }

        /// <summary>
        /// The UltraEdit64Bit1AppFolder folder.
        /// </summary>
        [RepositoryFolder("14d3eb5d-b572-4d62-a4c6-aada384fa128")]
        public partial class UltraEdit64Bit1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _homeInfo;
            RepoItemInfo _findreplaceinfilesInfo;

            /// <summary>
            /// Creates a new UltraEdit64Bit1  folder.
            /// </summary>
            public UltraEdit64Bit1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("UltraEdit64Bit1", "/form[@title~'UltraEdit 64-bi']", parentFolder, 30000, null, true, "14d3eb5d-b572-4d62-a4c6-aada384fa128", "")
            {
                _homeInfo = new RepoItemInfo(this, "Home", ".//toolbar[@accessiblerole='ToolBar']//tabpage[@accessiblename='Home']", "", 30000, null, "cb25d3f5-e9bf-41e3-9d6b-f56b8932e654");
                _findreplaceinfilesInfo = new RepoItemInfo(this, "FindReplaceInFiles", ".//toolbar[@accessiblename='Home']//button[@accessiblename='Find/replace in files']", ".//button[@accessiblename='Find/replace in files']", 30000, null, "6525ea1e-b645-4149-82af-0ca6b5a97051");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("14d3eb5d-b572-4d62-a4c6-aada384fa128")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("14d3eb5d-b572-4d62-a4c6-aada384fa128")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Home item.
            /// </summary>
            [RepositoryItem("cb25d3f5-e9bf-41e3-9d6b-f56b8932e654")]
            public virtual Ranorex.TabPage Home
            {
                get
                {
                    return _homeInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Home item info.
            /// </summary>
            [RepositoryItemInfo("cb25d3f5-e9bf-41e3-9d6b-f56b8932e654")]
            public virtual RepoItemInfo HomeInfo
            {
                get
                {
                    return _homeInfo;
                }
            }

            /// <summary>
            /// The FindReplaceInFiles item.
            /// </summary>
            [RepositoryItem("6525ea1e-b645-4149-82af-0ca6b5a97051")]
            public virtual Ranorex.Button FindReplaceInFiles
            {
                get
                {
                    return _findreplaceinfilesInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The FindReplaceInFiles item info.
            /// </summary>
            [RepositoryItemInfo("6525ea1e-b645-4149-82af-0ca6b5a97051")]
            public virtual RepoItemInfo FindReplaceInFilesInfo
            {
                get
                {
                    return _findreplaceinfilesInfo;
                }
            }
        }

        /// <summary>
        /// The FormEdit1UltraEdit64Bit1AppFolder folder.
        /// </summary>
        [RepositoryFolder("b8c74d4a-37e7-48e7-9c36-261f15ee2c2b")]
        public partial class FormEdit1UltraEdit64Bit1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _findInfo;

            /// <summary>
            /// Creates a new FormEdit1UltraEdit64Bit1  folder.
            /// </summary>
            public FormEdit1UltraEdit64Bit1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("FormEdit1UltraEdit64Bit1", "/form[@processname='uedit64']", parentFolder, 30000, null, false, "b8c74d4a-37e7-48e7-9c36-261f15ee2c2b", "")
            {
                _findInfo = new RepoItemInfo(this, "Find", "?/?/toolbar[@accessiblename=' ']/toolbar[@accessiblename='Home']/?/?/button[@accessiblename='Find']", ".//button[@accessiblename='Find']", 30000, null, "31457883-5708-4286-98c6-d942a05df49c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b8c74d4a-37e7-48e7-9c36-261f15ee2c2b")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b8c74d4a-37e7-48e7-9c36-261f15ee2c2b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Find item.
            /// </summary>
            [RepositoryItem("31457883-5708-4286-98c6-d942a05df49c")]
            public virtual Ranorex.Button Find
            {
                get
                {
                    return _findInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Find item info.
            /// </summary>
            [RepositoryItemInfo("31457883-5708-4286-98c6-d942a05df49c")]
            public virtual RepoItemInfo FindInfo
            {
                get
                {
                    return _findInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
